spring:
  application:
    name: tobe_blog
  profiles:
    active: @active.target.profile@
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3000
  mail:
    host: smtp.qq.com    # Change to actual SMTP server
    port: 587            # Common SMTP port
    username: ${MAIL_USERNAME}  # Replace with actual email
    password: ${MAIL_PASSWORD}  # Replace with actual password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
jwt:
  # 256 digits secret key, remember to replace before go live to prod
  secret:
    access: 482B4D6251655468576D597133743677397A24432646294A404E635266556A58
    refresh: 38782F413F4428472B4B6250645367566B597033733676397924422645294840
  # millis time to expire, by default access expire time 15 mins and refresh expire time 24 hours
  expire:
    # access: 900000
    access: 86400000
    refresh: 864000000
security-context:
  enable: true
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
mail:
  mail-from: 474504303@qq.com