spring:
  datasource:
    url: jdbc:mysql://rm-wz99x61sx0ptz4c41wo.mysql.rds.aliyuncs.com:3306/tobe_blog_test?useUnicode=true&character_set_server=utf8mb4
    charset: utf8mb4
    username: tobe
    password: 19920215cx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: tobe_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000