spring:
  datasource:
    url: jdbc:mysql://rm-wz99751n4ub3707x4fo.mysql.rds.aliyuncs.com:3306/tobe_blog_test?useUnicode=true&character_set_server=utf8mb4
    charset: utf8mb4
    username: tobe
    password: 19920215#Cx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: tobe_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.qq.com
    port: 587
    username: 474504303@qq.com
    password: { your-password }
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

# App-specific configuration
app:
  frontend-url: http://localhost:3000
