spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username:
    password:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: tobe_Hikari_Pool
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      data-locations: classpath:schema/data.sql
      schema-locations: classpath:schema/table.sql
    


